(dp1
S'output'
p2
S"<type 'exceptions.UnboundLocalError'> local variable 'dict' referenced before assignment"
p3
sS'layer'
p4
S'/home/vedant/Desktop/web2py/applications/garden_2_may/controllers/restaurant.py'
p5
sS'code'
p6
S"# -*- coding: utf-8 -*-\nresponse.menu.append(['Homepage',False,URL('restaurant','index')])\nresponse.menu+=[['Manage Orders',False,URL('restaurant','manage_orders')],['Change Menu',False,URL('manage_menu')]]\n\ndef index():\n    return dict(mesg=userauth.is_logged_in(),m2=resauth.user_id)\n\ndef user():\n    return dict(form=resauth())\n\n@resauth.requires_login()\ndef manage_menu():\n    response.title='Manage your menu'\n    addform=SQLFORM(db.dish)\n    if addform.process().accepted:\n        response.flash='%s has been added to the menu' %(addform.vars.name)\n    elif addform.errors:\n        response.flash='Please correct the errors and try again'\n    modifyform=SQLFORM.factory(Field('name','reference\\\n                               dish',requires=IS_IN_DB(db(db.dish.provider==resauth.user_id),db.dish.name)),\n                               Field('price',requires=IS_EMPTY_OR(IS_INT_IN_RANGE(17,None))),\n                               Field('description',length=1024),\n                               Field('image','upload',requires=IS_EMPTY_OR(IS_IMAGE(error_message='Uploaded file must be\\\n                               an image'))),\n                               table_name='modifyform_dummy_table')\n    if modifyform.process().accepted:\n     #   try:\n        q=db.dish.provider==resauth.user_id\n        q&=db.dish.name==modifyform.vars.name\n        dict={}\n        if modifyform.vars.price:\n            dict['price']=modifyform.vars.price\n        if modifyform.vars.description:\n            dict['description']=modifyform.vars.description\n        if modifyform.vars.image:\n            dict['image']=modifyform.vars.image\n        db(q).update(dict)\n        response.flash='Sucessfully updated'\n       #except:\n       #response.flash='Unexpected error occoured'\n    elif modifyform.errors:\n        response.flash='Please correct the errors'\n    return dict(addform=addform,modifyform=modifyform)\n\n@resauth.requires_login()\ndef manage_orders():\n    q=db.dish.provider==resauth.user_id\n    q&=db.dish.id==db.orders.item_id\n    rows=db(q).select(db.orders.ALL,db.dish.ALL)\n    return dict(rows=rows)\n\nresponse._vars=response._caller(manage_menu)\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/vedant/Desktop/web2py/gluon/restricted.py", line 224, in restricted\n    exec ccode in environment\n  File "/home/vedant/Desktop/web2py/applications/garden_2_may/controllers/restaurant.py", line 52, in <module>\n  File "/home/vedant/Desktop/web2py/gluon/globals.py", line 393, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/vedant/Desktop/web2py/gluon/tools.py", line 3444, in f\n    return action(*a, **b)\n  File "/home/vedant/Desktop/web2py/applications/garden_2_may/controllers/restaurant.py", line 43, in manage_menu\n    return dict(addform=addform,modifyform=modifyform)\nUnboundLocalError: local variable \'dict\' referenced before assignment\n'
p11
s.